services:
  postgres:
    image: postgres:15
    container_name: postgres-dev
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: myapp
    ports:
      - '${PG_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    container_name: redis-dev
    image: bitnami/redis:latest
    restart: unless-stopped
    ports:
      - '${REDIS_PORT}:6379'
    environment:
      - REDIS_PASSWORD=${REDIS_PASS}
    volumes:
      - redis_data:/bitnami/redis/data

volumes:
  postgres_data:
  redis_data:
